//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//havli//source//repos//ClosedXML.Parser//src//ClosedXML.ANTLR//FormulaParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


// ANTLR generated file is marked as a non-CLS compliant, but that is not necessary, because whole assembly is not CLS compliant.
#pragma warning disable 3021

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class FormulaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		REF_CONSTANT=1, NONREF_ERRORS=2, LOGICAL_CONSTANT=3, NUMERICAL_CONSTANT=4, 
		STRING_CONSTANT=5, POW=6, MULT=7, DIV=8, PLUS=9, MINUS=10, CONCAT=11, 
		EQUAL=12, NOT_EQUAL=13, LESS_OR_EQUAL_THAN=14, LESS_THAN=15, GREATER_OR_EQUAL_THAN=16, 
		GREATER_THAN=17, PERCENT=18, SEMICOLON=19, COLON=20, OPEN_BRACE=21, CLOSE_BRACE=22, 
		OPEN_CURLY=23, CLOSE_CURLY=24, COMMA=25, SPACE=26, INTERSECT=27, SPILL=28, 
		BOOK_PREFIX=29, BANG_REFERENCE=30, SHEET_RANGE_PREFIX=31, SINGLE_SHEET_PREFIX=32, 
		A1_CELL=33, A1_SPAN_REFERENCE=34, REF_FUNCTION_LIST=35, CELL_FUNCTION_LIST=36, 
		USER_DEFINED_FUNCTION_NAME=37, NAME=38, INTRA_TABLE_REFERENCE=39;
	public const int
		RULE_formula = 0, RULE_expression = 1, RULE_concat_expression = 2, RULE_additive_expression = 3, 
		RULE_multiplying_expression = 4, RULE_pow_expression = 5, RULE_percent_expression = 6, 
		RULE_prefix_atom_expression = 7, RULE_atom_expression = 8, RULE_ref_expression = 9, 
		RULE_ref_implicit_expression = 10, RULE_ref_intersection_expression = 11, 
		RULE_ref_range_expression = 12, RULE_ref_spill_expression = 13, RULE_ref_atom_expression = 14, 
		RULE_constant = 15, RULE_constant_list_rows = 16, RULE_constant_list_row = 17, 
		RULE_cell_reference = 18, RULE_a1_reference = 19, RULE_argument_list = 20, 
		RULE_arg_expression = 21, RULE_arg_concat_expression = 22, RULE_arg_additive_expression = 23, 
		RULE_arg_multiplying_expression = 24, RULE_arg_pow_expression = 25, RULE_arg_percent_expression = 26, 
		RULE_arg_prefix_atom_expression = 27, RULE_arg_atom_expression = 28, RULE_name_reference = 29, 
		RULE_structure_reference = 30, RULE_table_identifier = 31, RULE_table_name = 32, 
		RULE_ref_function_call = 33, RULE_function_call = 34;
	public static readonly string[] ruleNames = {
		"formula", "expression", "concat_expression", "additive_expression", "multiplying_expression", 
		"pow_expression", "percent_expression", "prefix_atom_expression", "atom_expression", 
		"ref_expression", "ref_implicit_expression", "ref_intersection_expression", 
		"ref_range_expression", "ref_spill_expression", "ref_atom_expression", 
		"constant", "constant_list_rows", "constant_list_row", "cell_reference", 
		"a1_reference", "argument_list", "arg_expression", "arg_concat_expression", 
		"arg_additive_expression", "arg_multiplying_expression", "arg_pow_expression", 
		"arg_percent_expression", "arg_prefix_atom_expression", "arg_atom_expression", 
		"name_reference", "structure_reference", "table_identifier", "table_name", 
		"ref_function_call", "function_call"
	};

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "REF_CONSTANT", "NONREF_ERRORS", "LOGICAL_CONSTANT", "NUMERICAL_CONSTANT", 
		"STRING_CONSTANT", "POW", "MULT", "DIV", "PLUS", "MINUS", "CONCAT", "EQUAL", 
		"NOT_EQUAL", "LESS_OR_EQUAL_THAN", "LESS_THAN", "GREATER_OR_EQUAL_THAN", 
		"GREATER_THAN", "PERCENT", "SEMICOLON", "COLON", "OPEN_BRACE", "CLOSE_BRACE", 
		"OPEN_CURLY", "CLOSE_CURLY", "COMMA", "SPACE", "INTERSECT", "SPILL", "BOOK_PREFIX", 
		"BANG_REFERENCE", "SHEET_RANGE_PREFIX", "SINGLE_SHEET_PREFIX", "A1_CELL", 
		"A1_SPAN_REFERENCE", "REF_FUNCTION_LIST", "CELL_FUNCTION_LIST", "USER_DEFINED_FUNCTION_NAME", 
		"NAME", "INTRA_TABLE_REFERENCE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FormulaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FormulaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FormulaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FormulaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FormulaContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FormulaParser.Eof, 0); }
		public FormulaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formula; } }
	}

	[RuleVersion(0)]
	public FormulaContext formula() {
		FormulaContext _localctx = new FormulaContext(Context, State);
		EnterRule(_localctx, 0, RULE_formula);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			expression();
			State = 71;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Concat_expressionContext[] concat_expression() {
			return GetRuleContexts<Concat_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Concat_expressionContext concat_expression(int i) {
			return GetRuleContext<Concat_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_OR_EQUAL_THAN() { return GetTokens(FormulaParser.GREATER_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.GREATER_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_OR_EQUAL_THAN() { return GetTokens(FormulaParser.LESS_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.LESS_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_THAN() { return GetTokens(FormulaParser.LESS_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_THAN(int i) {
			return GetToken(FormulaParser.LESS_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_THAN() { return GetTokens(FormulaParser.GREATER_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_THAN(int i) {
			return GetToken(FormulaParser.GREATER_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NOT_EQUAL() { return GetTokens(FormulaParser.NOT_EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT_EQUAL(int i) {
			return GetToken(FormulaParser.NOT_EQUAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EQUAL() { return GetTokens(FormulaParser.EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL(int i) {
			return GetToken(FormulaParser.EQUAL, i);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 2, RULE_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			concat_expression();
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) {
				{
				{
				State = 74;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 75;
				concat_expression();
				}
				}
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Concat_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Additive_expressionContext[] additive_expression() {
			return GetRuleContexts<Additive_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Additive_expressionContext additive_expression(int i) {
			return GetRuleContext<Additive_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CONCAT() { return GetTokens(FormulaParser.CONCAT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONCAT(int i) {
			return GetToken(FormulaParser.CONCAT, i);
		}
		public Concat_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_concat_expression; } }
	}

	[RuleVersion(0)]
	public Concat_expressionContext concat_expression() {
		Concat_expressionContext _localctx = new Concat_expressionContext(Context, State);
		EnterRule(_localctx, 4, RULE_concat_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			additive_expression();
			State = 86;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CONCAT) {
				{
				{
				State = 82;
				Match(CONCAT);
				State = 83;
				additive_expression();
				}
				}
				State = 88;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Additive_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Multiplying_expressionContext[] multiplying_expression() {
			return GetRuleContexts<Multiplying_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Multiplying_expressionContext multiplying_expression(int i) {
			return GetRuleContext<Multiplying_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(FormulaParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(FormulaParser.PLUS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MINUS() { return GetTokens(FormulaParser.MINUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS(int i) {
			return GetToken(FormulaParser.MINUS, i);
		}
		public Additive_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additive_expression; } }
	}

	[RuleVersion(0)]
	public Additive_expressionContext additive_expression() {
		Additive_expressionContext _localctx = new Additive_expressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_additive_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89;
			multiplying_expression();
			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 90;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 91;
				multiplying_expression();
				}
				}
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Multiplying_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Pow_expressionContext[] pow_expression() {
			return GetRuleContexts<Pow_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pow_expressionContext pow_expression(int i) {
			return GetRuleContext<Pow_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULT() { return GetTokens(FormulaParser.MULT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT(int i) {
			return GetToken(FormulaParser.MULT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIV() { return GetTokens(FormulaParser.DIV); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV(int i) {
			return GetToken(FormulaParser.DIV, i);
		}
		public Multiplying_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplying_expression; } }
	}

	[RuleVersion(0)]
	public Multiplying_expressionContext multiplying_expression() {
		Multiplying_expressionContext _localctx = new Multiplying_expressionContext(Context, State);
		EnterRule(_localctx, 8, RULE_multiplying_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			pow_expression();
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULT || _la==DIV) {
				{
				{
				State = 98;
				_la = TokenStream.LA(1);
				if ( !(_la==MULT || _la==DIV) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 99;
				pow_expression();
				}
				}
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pow_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Percent_expressionContext[] percent_expression() {
			return GetRuleContexts<Percent_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Percent_expressionContext percent_expression(int i) {
			return GetRuleContext<Percent_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] POW() { return GetTokens(FormulaParser.POW); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW(int i) {
			return GetToken(FormulaParser.POW, i);
		}
		public Pow_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pow_expression; } }
	}

	[RuleVersion(0)]
	public Pow_expressionContext pow_expression() {
		Pow_expressionContext _localctx = new Pow_expressionContext(Context, State);
		EnterRule(_localctx, 10, RULE_pow_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			percent_expression();
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POW) {
				{
				{
				State = 106;
				Match(POW);
				State = 107;
				percent_expression();
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Percent_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Prefix_atom_expressionContext prefix_atom_expression() {
			return GetRuleContext<Prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PERCENT() { return GetTokens(FormulaParser.PERCENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PERCENT(int i) {
			return GetToken(FormulaParser.PERCENT, i);
		}
		public Percent_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_percent_expression; } }
	}

	[RuleVersion(0)]
	public Percent_expressionContext percent_expression() {
		Percent_expressionContext _localctx = new Percent_expressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_percent_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113;
			prefix_atom_expression();
			State = 117;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PERCENT) {
				{
				{
				State = 114;
				Match(PERCENT);
				}
				}
				State = 119;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prefix_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Prefix_atom_expressionContext prefix_atom_expression() {
			return GetRuleContext<Prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(FormulaParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(FormulaParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Atom_expressionContext atom_expression() {
			return GetRuleContext<Atom_expressionContext>(0);
		}
		public Prefix_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prefix_atom_expression; } }
	}

	[RuleVersion(0)]
	public Prefix_atom_expressionContext prefix_atom_expression() {
		Prefix_atom_expressionContext _localctx = new Prefix_atom_expressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_prefix_atom_expression);
		int _la;
		try {
			State = 123;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
			case MINUS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 120;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 121;
				prefix_atom_expression();
				}
				break;
			case REF_CONSTANT:
			case NONREF_ERRORS:
			case LOGICAL_CONSTANT:
			case NUMERICAL_CONSTANT:
			case STRING_CONSTANT:
			case OPEN_BRACE:
			case OPEN_CURLY:
			case INTERSECT:
			case BOOK_PREFIX:
			case BANG_REFERENCE:
			case SHEET_RANGE_PREFIX:
			case SINGLE_SHEET_PREFIX:
			case A1_CELL:
			case A1_SPAN_REFERENCE:
			case REF_FUNCTION_LIST:
			case CELL_FUNCTION_LIST:
			case USER_DEFINED_FUNCTION_NAME:
			case NAME:
			case INTRA_TABLE_REFERENCE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 122;
				atom_expression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_expressionContext ref_expression() {
			return GetRuleContext<Ref_expressionContext>(0);
		}
		public Atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom_expression; } }
	}

	[RuleVersion(0)]
	public Atom_expressionContext atom_expression() {
		Atom_expressionContext _localctx = new Atom_expressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_atom_expression);
		try {
			State = 132;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 125;
				constant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 126;
				Match(OPEN_BRACE);
				State = 127;
				expression();
				State = 128;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 130;
				function_call();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 131;
				ref_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext[] ref_implicit_expression() {
			return GetRuleContexts<Ref_implicit_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression(int i) {
			return GetRuleContext<Ref_implicit_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Ref_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_expression; } }
	}

	[RuleVersion(0)]
	public Ref_expressionContext ref_expression() {
		Ref_expressionContext _localctx = new Ref_expressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_ref_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134;
			ref_implicit_expression();
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 135;
				Match(COMMA);
				State = 136;
				ref_implicit_expression();
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_implicit_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERSECT() { return GetToken(FormulaParser.INTERSECT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_intersection_expressionContext ref_intersection_expression() {
			return GetRuleContext<Ref_intersection_expressionContext>(0);
		}
		public Ref_implicit_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_implicit_expression; } }
	}

	[RuleVersion(0)]
	public Ref_implicit_expressionContext ref_implicit_expression() {
		Ref_implicit_expressionContext _localctx = new Ref_implicit_expressionContext(Context, State);
		EnterRule(_localctx, 20, RULE_ref_implicit_expression);
		try {
			State = 145;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTERSECT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 142;
				Match(INTERSECT);
				State = 143;
				ref_implicit_expression();
				}
				break;
			case REF_CONSTANT:
			case OPEN_BRACE:
			case BOOK_PREFIX:
			case BANG_REFERENCE:
			case SHEET_RANGE_PREFIX:
			case SINGLE_SHEET_PREFIX:
			case A1_CELL:
			case A1_SPAN_REFERENCE:
			case REF_FUNCTION_LIST:
			case NAME:
			case INTRA_TABLE_REFERENCE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 144;
				ref_intersection_expression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_intersection_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_range_expressionContext[] ref_range_expression() {
			return GetRuleContexts<Ref_range_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_range_expressionContext ref_range_expression(int i) {
			return GetRuleContext<Ref_range_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(FormulaParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(FormulaParser.SPACE, i);
		}
		public Ref_intersection_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_intersection_expression; } }
	}

	[RuleVersion(0)]
	public Ref_intersection_expressionContext ref_intersection_expression() {
		Ref_intersection_expressionContext _localctx = new Ref_intersection_expressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_ref_intersection_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			ref_range_expression();
			State = 152;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SPACE) {
				{
				{
				State = 148;
				Match(SPACE);
				State = 149;
				ref_range_expression();
				}
				}
				State = 154;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_range_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_spill_expressionContext[] ref_spill_expression() {
			return GetRuleContexts<Ref_spill_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_spill_expressionContext ref_spill_expression(int i) {
			return GetRuleContext<Ref_spill_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COLON() { return GetTokens(FormulaParser.COLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON(int i) {
			return GetToken(FormulaParser.COLON, i);
		}
		public Ref_range_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_range_expression; } }
	}

	[RuleVersion(0)]
	public Ref_range_expressionContext ref_range_expression() {
		Ref_range_expressionContext _localctx = new Ref_range_expressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_ref_range_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			ref_spill_expression();
			State = 160;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COLON) {
				{
				{
				State = 156;
				Match(COLON);
				State = 157;
				ref_spill_expression();
				}
				}
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_spill_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ref_atom_expressionContext ref_atom_expression() {
			return GetRuleContext<Ref_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPILL() { return GetToken(FormulaParser.SPILL, 0); }
		public Ref_spill_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_spill_expression; } }
	}

	[RuleVersion(0)]
	public Ref_spill_expressionContext ref_spill_expression() {
		Ref_spill_expressionContext _localctx = new Ref_spill_expressionContext(Context, State);
		EnterRule(_localctx, 26, RULE_ref_spill_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			ref_atom_expression();
			State = 165;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPILL) {
				{
				State = 164;
				Match(SPILL);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT() { return GetToken(FormulaParser.REF_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Ref_expressionContext ref_expression() {
			return GetRuleContext<Ref_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Cell_referenceContext cell_reference() {
			return GetRuleContext<Cell_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_function_callContext ref_function_call() {
			return GetRuleContext<Ref_function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_referenceContext name_reference() {
			return GetRuleContext<Name_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Structure_referenceContext structure_reference() {
			return GetRuleContext<Structure_referenceContext>(0);
		}
		public Ref_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_atom_expression; } }
	}

	[RuleVersion(0)]
	public Ref_atom_expressionContext ref_atom_expression() {
		Ref_atom_expressionContext _localctx = new Ref_atom_expressionContext(Context, State);
		EnterRule(_localctx, 28, RULE_ref_atom_expression);
		try {
			State = 176;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 167;
				Match(REF_CONSTANT);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 168;
				Match(OPEN_BRACE);
				State = 169;
				ref_expression();
				State = 170;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 172;
				cell_reference();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 173;
				ref_function_call();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 174;
				name_reference();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 175;
				structure_reference();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConstantContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NONREF_ERRORS() { return GetToken(FormulaParser.NONREF_ERRORS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LOGICAL_CONSTANT() { return GetToken(FormulaParser.LOGICAL_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMERICAL_CONSTANT() { return GetToken(FormulaParser.NUMERICAL_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_CONSTANT() { return GetToken(FormulaParser.STRING_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_CURLY() { return GetToken(FormulaParser.OPEN_CURLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowsContext constant_list_rows() {
			return GetRuleContext<Constant_list_rowsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_CURLY() { return GetToken(FormulaParser.CLOSE_CURLY, 0); }
		public ConstantContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant; } }
	}

	[RuleVersion(0)]
	public ConstantContext constant() {
		ConstantContext _localctx = new ConstantContext(Context, State);
		EnterRule(_localctx, 30, RULE_constant);
		try {
			State = 186;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NONREF_ERRORS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 178;
				Match(NONREF_ERRORS);
				}
				break;
			case LOGICAL_CONSTANT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179;
				Match(LOGICAL_CONSTANT);
				}
				break;
			case NUMERICAL_CONSTANT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 180;
				Match(NUMERICAL_CONSTANT);
				}
				break;
			case STRING_CONSTANT:
				EnterOuterAlt(_localctx, 4);
				{
				State = 181;
				Match(STRING_CONSTANT);
				}
				break;
			case OPEN_CURLY:
				EnterOuterAlt(_localctx, 5);
				{
				State = 182;
				Match(OPEN_CURLY);
				State = 183;
				constant_list_rows();
				State = 184;
				Match(CLOSE_CURLY);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Constant_list_rowsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowContext[] constant_list_row() {
			return GetRuleContexts<Constant_list_rowContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Constant_list_rowContext constant_list_row(int i) {
			return GetRuleContext<Constant_list_rowContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMICOLON() { return GetTokens(FormulaParser.SEMICOLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON(int i) {
			return GetToken(FormulaParser.SEMICOLON, i);
		}
		public Constant_list_rowsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant_list_rows; } }
	}

	[RuleVersion(0)]
	public Constant_list_rowsContext constant_list_rows() {
		Constant_list_rowsContext _localctx = new Constant_list_rowsContext(Context, State);
		EnterRule(_localctx, 32, RULE_constant_list_rows);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			constant_list_row();
			State = 193;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SEMICOLON) {
				{
				{
				State = 189;
				Match(SEMICOLON);
				State = 190;
				constant_list_row();
				}
				}
				State = 195;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Constant_list_rowContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext[] constant() {
			return GetRuleContexts<ConstantContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant(int i) {
			return GetRuleContext<ConstantContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REF_CONSTANT() { return GetTokens(FormulaParser.REF_CONSTANT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT(int i) {
			return GetToken(FormulaParser.REF_CONSTANT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Constant_list_rowContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_constant_list_row; } }
	}

	[RuleVersion(0)]
	public Constant_list_rowContext constant_list_row() {
		Constant_list_rowContext _localctx = new Constant_list_rowContext(Context, State);
		EnterRule(_localctx, 34, RULE_constant_list_row);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NONREF_ERRORS:
			case LOGICAL_CONSTANT:
			case NUMERICAL_CONSTANT:
			case STRING_CONSTANT:
			case OPEN_CURLY:
				{
				State = 196;
				constant();
				}
				break;
			case REF_CONSTANT:
				{
				State = 197;
				Match(REF_CONSTANT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 207;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 200;
				Match(COMMA);
				State = 203;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case NONREF_ERRORS:
				case LOGICAL_CONSTANT:
				case NUMERICAL_CONSTANT:
				case STRING_CONSTANT:
				case OPEN_CURLY:
					{
					State = 201;
					constant();
					}
					break;
				case REF_CONSTANT:
					{
					State = 202;
					Match(REF_CONSTANT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				}
				State = 209;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cell_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public A1_referenceContext a1_reference() {
			return GetRuleContext<A1_referenceContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BANG_REFERENCE() { return GetToken(FormulaParser.BANG_REFERENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SHEET_RANGE_PREFIX() { return GetToken(FormulaParser.SHEET_RANGE_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_CONSTANT() { return GetToken(FormulaParser.REF_CONSTANT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FormulaParser.COLON, 0); }
		public Cell_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cell_reference; } }
	}

	[RuleVersion(0)]
	public Cell_referenceContext cell_reference() {
		Cell_referenceContext _localctx = new Cell_referenceContext(Context, State);
		EnterRule(_localctx, 36, RULE_cell_reference);
		try {
			State = 223;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case A1_CELL:
			case A1_SPAN_REFERENCE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 210;
				a1_reference();
				}
				break;
			case BANG_REFERENCE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 211;
				Match(BANG_REFERENCE);
				}
				break;
			case SHEET_RANGE_PREFIX:
				EnterOuterAlt(_localctx, 3);
				{
				State = 212;
				Match(SHEET_RANGE_PREFIX);
				State = 213;
				a1_reference();
				}
				break;
			case SINGLE_SHEET_PREFIX:
				EnterOuterAlt(_localctx, 4);
				{
				State = 214;
				Match(SINGLE_SHEET_PREFIX);
				State = 217;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case A1_CELL:
				case A1_SPAN_REFERENCE:
					{
					State = 215;
					a1_reference();
					}
					break;
				case REF_CONSTANT:
					{
					State = 216;
					Match(REF_CONSTANT);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case NAME:
				EnterOuterAlt(_localctx, 5);
				{
				State = 219;
				Match(NAME);
				State = 220;
				Match(COLON);
				State = 221;
				Match(SINGLE_SHEET_PREFIX);
				State = 222;
				a1_reference();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class A1_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] A1_CELL() { return GetTokens(FormulaParser.A1_CELL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A1_CELL(int i) {
			return GetToken(FormulaParser.A1_CELL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(FormulaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode A1_SPAN_REFERENCE() { return GetToken(FormulaParser.A1_SPAN_REFERENCE, 0); }
		public A1_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_a1_reference; } }
	}

	[RuleVersion(0)]
	public A1_referenceContext a1_reference() {
		A1_referenceContext _localctx = new A1_referenceContext(Context, State);
		EnterRule(_localctx, 38, RULE_a1_reference);
		try {
			State = 230;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 225;
				Match(A1_CELL);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 226;
				Match(A1_CELL);
				State = 227;
				Match(COLON);
				State = 228;
				Match(A1_CELL);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 229;
				Match(A1_SPAN_REFERENCE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Argument_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Arg_expressionContext[] arg_expression() {
			return GetRuleContexts<Arg_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_expressionContext arg_expression(int i) {
			return GetRuleContext<Arg_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(FormulaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(FormulaParser.COMMA, i);
		}
		public Argument_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument_list; } }
	}

	[RuleVersion(0)]
	public Argument_listContext argument_list() {
		Argument_listContext _localctx = new Argument_listContext(Context, State);
		EnterRule(_localctx, 40, RULE_argument_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 233;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1099119461950L) != 0)) {
				{
				State = 232;
				arg_expression();
				}
			}

			State = 241;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 235;
				Match(COMMA);
				State = 237;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1099119461950L) != 0)) {
					{
					State = 236;
					arg_expression();
					}
				}

				}
				}
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 244;
			Match(CLOSE_BRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_concat_expressionContext[] arg_concat_expression() {
			return GetRuleContexts<Arg_concat_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_concat_expressionContext arg_concat_expression(int i) {
			return GetRuleContext<Arg_concat_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_OR_EQUAL_THAN() { return GetTokens(FormulaParser.GREATER_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.GREATER_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_OR_EQUAL_THAN() { return GetTokens(FormulaParser.LESS_OR_EQUAL_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_OR_EQUAL_THAN(int i) {
			return GetToken(FormulaParser.LESS_OR_EQUAL_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LESS_THAN() { return GetTokens(FormulaParser.LESS_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS_THAN(int i) {
			return GetToken(FormulaParser.LESS_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] GREATER_THAN() { return GetTokens(FormulaParser.GREATER_THAN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GREATER_THAN(int i) {
			return GetToken(FormulaParser.GREATER_THAN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NOT_EQUAL() { return GetTokens(FormulaParser.NOT_EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT_EQUAL(int i) {
			return GetToken(FormulaParser.NOT_EQUAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] EQUAL() { return GetTokens(FormulaParser.EQUAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL(int i) {
			return GetToken(FormulaParser.EQUAL, i);
		}
		public Arg_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_expression; } }
	}

	[RuleVersion(0)]
	public Arg_expressionContext arg_expression() {
		Arg_expressionContext _localctx = new Arg_expressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_arg_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 246;
			arg_concat_expression();
			State = 251;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) {
				{
				{
				State = 247;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 258048L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 248;
				arg_concat_expression();
				}
				}
				State = 253;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_concat_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_additive_expressionContext[] arg_additive_expression() {
			return GetRuleContexts<Arg_additive_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_additive_expressionContext arg_additive_expression(int i) {
			return GetRuleContext<Arg_additive_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CONCAT() { return GetTokens(FormulaParser.CONCAT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONCAT(int i) {
			return GetToken(FormulaParser.CONCAT, i);
		}
		public Arg_concat_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_concat_expression; } }
	}

	[RuleVersion(0)]
	public Arg_concat_expressionContext arg_concat_expression() {
		Arg_concat_expressionContext _localctx = new Arg_concat_expressionContext(Context, State);
		EnterRule(_localctx, 44, RULE_arg_concat_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 254;
			arg_additive_expression();
			State = 259;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CONCAT) {
				{
				{
				State = 255;
				Match(CONCAT);
				State = 256;
				arg_additive_expression();
				}
				}
				State = 261;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_additive_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_multiplying_expressionContext[] arg_multiplying_expression() {
			return GetRuleContexts<Arg_multiplying_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_multiplying_expressionContext arg_multiplying_expression(int i) {
			return GetRuleContext<Arg_multiplying_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(FormulaParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(FormulaParser.PLUS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MINUS() { return GetTokens(FormulaParser.MINUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS(int i) {
			return GetToken(FormulaParser.MINUS, i);
		}
		public Arg_additive_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_additive_expression; } }
	}

	[RuleVersion(0)]
	public Arg_additive_expressionContext arg_additive_expression() {
		Arg_additive_expressionContext _localctx = new Arg_additive_expressionContext(Context, State);
		EnterRule(_localctx, 46, RULE_arg_additive_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262;
			arg_multiplying_expression();
			State = 267;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS || _la==MINUS) {
				{
				{
				State = 263;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 264;
				arg_multiplying_expression();
				}
				}
				State = 269;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_multiplying_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_pow_expressionContext[] arg_pow_expression() {
			return GetRuleContexts<Arg_pow_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_pow_expressionContext arg_pow_expression(int i) {
			return GetRuleContext<Arg_pow_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULT() { return GetTokens(FormulaParser.MULT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT(int i) {
			return GetToken(FormulaParser.MULT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DIV() { return GetTokens(FormulaParser.DIV); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIV(int i) {
			return GetToken(FormulaParser.DIV, i);
		}
		public Arg_multiplying_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_multiplying_expression; } }
	}

	[RuleVersion(0)]
	public Arg_multiplying_expressionContext arg_multiplying_expression() {
		Arg_multiplying_expressionContext _localctx = new Arg_multiplying_expressionContext(Context, State);
		EnterRule(_localctx, 48, RULE_arg_multiplying_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 270;
			arg_pow_expression();
			State = 275;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULT || _la==DIV) {
				{
				{
				State = 271;
				_la = TokenStream.LA(1);
				if ( !(_la==MULT || _la==DIV) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 272;
				arg_pow_expression();
				}
				}
				State = 277;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_pow_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_percent_expressionContext[] arg_percent_expression() {
			return GetRuleContexts<Arg_percent_expressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Arg_percent_expressionContext arg_percent_expression(int i) {
			return GetRuleContext<Arg_percent_expressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] POW() { return GetTokens(FormulaParser.POW); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POW(int i) {
			return GetToken(FormulaParser.POW, i);
		}
		public Arg_pow_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_pow_expression; } }
	}

	[RuleVersion(0)]
	public Arg_pow_expressionContext arg_pow_expression() {
		Arg_pow_expressionContext _localctx = new Arg_pow_expressionContext(Context, State);
		EnterRule(_localctx, 50, RULE_arg_pow_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			arg_percent_expression();
			State = 283;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POW) {
				{
				{
				State = 279;
				Match(POW);
				State = 280;
				arg_percent_expression();
				}
				}
				State = 285;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_percent_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
			return GetRuleContext<Arg_prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PERCENT() { return GetToken(FormulaParser.PERCENT, 0); }
		public Arg_percent_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_percent_expression; } }
	}

	[RuleVersion(0)]
	public Arg_percent_expressionContext arg_percent_expression() {
		Arg_percent_expressionContext _localctx = new Arg_percent_expressionContext(Context, State);
		EnterRule(_localctx, 52, RULE_arg_percent_expression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286;
			arg_prefix_atom_expression();
			State = 288;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PERCENT) {
				{
				State = 287;
				Match(PERCENT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_prefix_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
			return GetRuleContext<Arg_prefix_atom_expressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(FormulaParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(FormulaParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Arg_atom_expressionContext arg_atom_expression() {
			return GetRuleContext<Arg_atom_expressionContext>(0);
		}
		public Arg_prefix_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_prefix_atom_expression; } }
	}

	[RuleVersion(0)]
	public Arg_prefix_atom_expressionContext arg_prefix_atom_expression() {
		Arg_prefix_atom_expressionContext _localctx = new Arg_prefix_atom_expressionContext(Context, State);
		EnterRule(_localctx, 54, RULE_arg_prefix_atom_expression);
		int _la;
		try {
			State = 293;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
			case MINUS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 290;
				_la = TokenStream.LA(1);
				if ( !(_la==PLUS || _la==MINUS) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 291;
				arg_prefix_atom_expression();
				}
				break;
			case REF_CONSTANT:
			case NONREF_ERRORS:
			case LOGICAL_CONSTANT:
			case NUMERICAL_CONSTANT:
			case STRING_CONSTANT:
			case OPEN_BRACE:
			case OPEN_CURLY:
			case INTERSECT:
			case BOOK_PREFIX:
			case BANG_REFERENCE:
			case SHEET_RANGE_PREFIX:
			case SINGLE_SHEET_PREFIX:
			case A1_CELL:
			case A1_SPAN_REFERENCE:
			case REF_FUNCTION_LIST:
			case CELL_FUNCTION_LIST:
			case USER_DEFINED_FUNCTION_NAME:
			case NAME:
			case INTRA_TABLE_REFERENCE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 292;
				arg_atom_expression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Arg_atom_expressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ConstantContext constant() {
			return GetRuleContext<ConstantContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPEN_BRACE() { return GetToken(FormulaParser.OPEN_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLOSE_BRACE() { return GetToken(FormulaParser.CLOSE_BRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Function_callContext function_call() {
			return GetRuleContext<Function_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ref_implicit_expressionContext ref_implicit_expression() {
			return GetRuleContext<Ref_implicit_expressionContext>(0);
		}
		public Arg_atom_expressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg_atom_expression; } }
	}

	[RuleVersion(0)]
	public Arg_atom_expressionContext arg_atom_expression() {
		Arg_atom_expressionContext _localctx = new Arg_atom_expressionContext(Context, State);
		EnterRule(_localctx, 56, RULE_arg_atom_expression);
		try {
			State = 302;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 295;
				constant();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 296;
				Match(OPEN_BRACE);
				State = 297;
				expression();
				State = 298;
				Match(CLOSE_BRACE);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 300;
				function_call();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 301;
				ref_implicit_expression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		public Name_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_reference; } }
	}

	[RuleVersion(0)]
	public Name_referenceContext name_reference() {
		Name_referenceContext _localctx = new Name_referenceContext(Context, State);
		EnterRule(_localctx, 58, RULE_name_reference);
		int _la;
		try {
			State = 307;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NAME:
				EnterOuterAlt(_localctx, 1);
				{
				State = 304;
				Match(NAME);
				}
				break;
			case BOOK_PREFIX:
			case SINGLE_SHEET_PREFIX:
				EnterOuterAlt(_localctx, 2);
				{
				State = 305;
				_la = TokenStream.LA(1);
				if ( !(_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 306;
				Match(NAME);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Structure_referenceContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTRA_TABLE_REFERENCE() { return GetToken(FormulaParser.INTRA_TABLE_REFERENCE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Table_identifierContext table_identifier() {
			return GetRuleContext<Table_identifierContext>(0);
		}
		public Structure_referenceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structure_reference; } }
	}

	[RuleVersion(0)]
	public Structure_referenceContext structure_reference() {
		Structure_referenceContext _localctx = new Structure_referenceContext(Context, State);
		EnterRule(_localctx, 60, RULE_structure_reference);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 310;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==BOOK_PREFIX || _la==NAME) {
				{
				State = 309;
				table_identifier();
				}
			}

			State = 312;
			Match(INTRA_TABLE_REFERENCE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_identifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		public Table_identifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_identifier; } }
	}

	[RuleVersion(0)]
	public Table_identifierContext table_identifier() {
		Table_identifierContext _localctx = new Table_identifierContext(Context, State);
		EnterRule(_localctx, 62, RULE_table_identifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 315;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==BOOK_PREFIX) {
				{
				State = 314;
				Match(BOOK_PREFIX);
				}
			}

			State = 317;
			table_name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAME() { return GetToken(FormulaParser.NAME, 0); }
		public Table_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_name; } }
	}

	[RuleVersion(0)]
	public Table_nameContext table_name() {
		Table_nameContext _localctx = new Table_nameContext(Context, State);
		EnterRule(_localctx, 64, RULE_table_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 319;
			Match(NAME);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ref_function_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REF_FUNCTION_LIST() { return GetToken(FormulaParser.REF_FUNCTION_LIST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Argument_listContext argument_list() {
			return GetRuleContext<Argument_listContext>(0);
		}
		public Ref_function_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ref_function_call; } }
	}

	[RuleVersion(0)]
	public Ref_function_callContext ref_function_call() {
		Ref_function_callContext _localctx = new Ref_function_callContext(Context, State);
		EnterRule(_localctx, 66, RULE_ref_function_call);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 321;
			Match(REF_FUNCTION_LIST);
			State = 322;
			argument_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Argument_listContext argument_list() {
			return GetRuleContext<Argument_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CELL_FUNCTION_LIST() { return GetToken(FormulaParser.CELL_FUNCTION_LIST, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USER_DEFINED_FUNCTION_NAME() { return GetToken(FormulaParser.USER_DEFINED_FUNCTION_NAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_SHEET_PREFIX() { return GetToken(FormulaParser.SINGLE_SHEET_PREFIX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOK_PREFIX() { return GetToken(FormulaParser.BOOK_PREFIX, 0); }
		public Function_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_call; } }
	}

	[RuleVersion(0)]
	public Function_callContext function_call() {
		Function_callContext _localctx = new Function_callContext(Context, State);
		EnterRule(_localctx, 68, RULE_function_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 329;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case CELL_FUNCTION_LIST:
				{
				State = 324;
				Match(CELL_FUNCTION_LIST);
				}
				break;
			case BOOK_PREFIX:
			case SINGLE_SHEET_PREFIX:
			case USER_DEFINED_FUNCTION_NAME:
				{
				State = 326;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) {
					{
					State = 325;
					_la = TokenStream.LA(1);
					if ( !(_la==BOOK_PREFIX || _la==SINGLE_SHEET_PREFIX) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
				}

				State = 328;
				Match(USER_DEFINED_FUNCTION_NAME);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 331;
			argument_list();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,39,334,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,2,30,7,30,2,31,7,31,2,32,7,32,2,33,7,33,2,34,7,34,1,0,1,0,1,
		0,1,1,1,1,1,1,5,1,77,8,1,10,1,12,1,80,9,1,1,2,1,2,1,2,5,2,85,8,2,10,2,
		12,2,88,9,2,1,3,1,3,1,3,5,3,93,8,3,10,3,12,3,96,9,3,1,4,1,4,1,4,5,4,101,
		8,4,10,4,12,4,104,9,4,1,5,1,5,1,5,5,5,109,8,5,10,5,12,5,112,9,5,1,6,1,
		6,5,6,116,8,6,10,6,12,6,119,9,6,1,7,1,7,1,7,3,7,124,8,7,1,8,1,8,1,8,1,
		8,1,8,1,8,1,8,3,8,133,8,8,1,9,1,9,1,9,5,9,138,8,9,10,9,12,9,141,9,9,1,
		10,1,10,1,10,3,10,146,8,10,1,11,1,11,1,11,5,11,151,8,11,10,11,12,11,154,
		9,11,1,12,1,12,1,12,5,12,159,8,12,10,12,12,12,162,9,12,1,13,1,13,3,13,
		166,8,13,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,177,8,14,1,
		15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,3,15,187,8,15,1,16,1,16,1,16,5,16,
		192,8,16,10,16,12,16,195,9,16,1,17,1,17,3,17,199,8,17,1,17,1,17,1,17,3,
		17,204,8,17,5,17,206,8,17,10,17,12,17,209,9,17,1,18,1,18,1,18,1,18,1,18,
		1,18,1,18,3,18,218,8,18,1,18,1,18,1,18,1,18,3,18,224,8,18,1,19,1,19,1,
		19,1,19,1,19,3,19,231,8,19,1,20,3,20,234,8,20,1,20,1,20,3,20,238,8,20,
		5,20,240,8,20,10,20,12,20,243,9,20,1,20,1,20,1,21,1,21,1,21,5,21,250,8,
		21,10,21,12,21,253,9,21,1,22,1,22,1,22,5,22,258,8,22,10,22,12,22,261,9,
		22,1,23,1,23,1,23,5,23,266,8,23,10,23,12,23,269,9,23,1,24,1,24,1,24,5,
		24,274,8,24,10,24,12,24,277,9,24,1,25,1,25,1,25,5,25,282,8,25,10,25,12,
		25,285,9,25,1,26,1,26,3,26,289,8,26,1,27,1,27,1,27,3,27,294,8,27,1,28,
		1,28,1,28,1,28,1,28,1,28,1,28,3,28,303,8,28,1,29,1,29,1,29,3,29,308,8,
		29,1,30,3,30,311,8,30,1,30,1,30,1,31,3,31,316,8,31,1,31,1,31,1,32,1,32,
		1,33,1,33,1,33,1,34,1,34,3,34,327,8,34,1,34,3,34,330,8,34,1,34,1,34,1,
		34,0,0,35,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,
		44,46,48,50,52,54,56,58,60,62,64,66,68,0,4,1,0,12,17,1,0,9,10,1,0,7,8,
		2,0,29,29,32,32,351,0,70,1,0,0,0,2,73,1,0,0,0,4,81,1,0,0,0,6,89,1,0,0,
		0,8,97,1,0,0,0,10,105,1,0,0,0,12,113,1,0,0,0,14,123,1,0,0,0,16,132,1,0,
		0,0,18,134,1,0,0,0,20,145,1,0,0,0,22,147,1,0,0,0,24,155,1,0,0,0,26,163,
		1,0,0,0,28,176,1,0,0,0,30,186,1,0,0,0,32,188,1,0,0,0,34,198,1,0,0,0,36,
		223,1,0,0,0,38,230,1,0,0,0,40,233,1,0,0,0,42,246,1,0,0,0,44,254,1,0,0,
		0,46,262,1,0,0,0,48,270,1,0,0,0,50,278,1,0,0,0,52,286,1,0,0,0,54,293,1,
		0,0,0,56,302,1,0,0,0,58,307,1,0,0,0,60,310,1,0,0,0,62,315,1,0,0,0,64,319,
		1,0,0,0,66,321,1,0,0,0,68,329,1,0,0,0,70,71,3,2,1,0,71,72,5,0,0,1,72,1,
		1,0,0,0,73,78,3,4,2,0,74,75,7,0,0,0,75,77,3,4,2,0,76,74,1,0,0,0,77,80,
		1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,3,1,0,0,0,80,78,1,0,0,0,81,86,3,
		6,3,0,82,83,5,11,0,0,83,85,3,6,3,0,84,82,1,0,0,0,85,88,1,0,0,0,86,84,1,
		0,0,0,86,87,1,0,0,0,87,5,1,0,0,0,88,86,1,0,0,0,89,94,3,8,4,0,90,91,7,1,
		0,0,91,93,3,8,4,0,92,90,1,0,0,0,93,96,1,0,0,0,94,92,1,0,0,0,94,95,1,0,
		0,0,95,7,1,0,0,0,96,94,1,0,0,0,97,102,3,10,5,0,98,99,7,2,0,0,99,101,3,
		10,5,0,100,98,1,0,0,0,101,104,1,0,0,0,102,100,1,0,0,0,102,103,1,0,0,0,
		103,9,1,0,0,0,104,102,1,0,0,0,105,110,3,12,6,0,106,107,5,6,0,0,107,109,
		3,12,6,0,108,106,1,0,0,0,109,112,1,0,0,0,110,108,1,0,0,0,110,111,1,0,0,
		0,111,11,1,0,0,0,112,110,1,0,0,0,113,117,3,14,7,0,114,116,5,18,0,0,115,
		114,1,0,0,0,116,119,1,0,0,0,117,115,1,0,0,0,117,118,1,0,0,0,118,13,1,0,
		0,0,119,117,1,0,0,0,120,121,7,1,0,0,121,124,3,14,7,0,122,124,3,16,8,0,
		123,120,1,0,0,0,123,122,1,0,0,0,124,15,1,0,0,0,125,133,3,30,15,0,126,127,
		5,21,0,0,127,128,3,2,1,0,128,129,5,22,0,0,129,133,1,0,0,0,130,133,3,68,
		34,0,131,133,3,18,9,0,132,125,1,0,0,0,132,126,1,0,0,0,132,130,1,0,0,0,
		132,131,1,0,0,0,133,17,1,0,0,0,134,139,3,20,10,0,135,136,5,25,0,0,136,
		138,3,20,10,0,137,135,1,0,0,0,138,141,1,0,0,0,139,137,1,0,0,0,139,140,
		1,0,0,0,140,19,1,0,0,0,141,139,1,0,0,0,142,143,5,27,0,0,143,146,3,20,10,
		0,144,146,3,22,11,0,145,142,1,0,0,0,145,144,1,0,0,0,146,21,1,0,0,0,147,
		152,3,24,12,0,148,149,5,26,0,0,149,151,3,24,12,0,150,148,1,0,0,0,151,154,
		1,0,0,0,152,150,1,0,0,0,152,153,1,0,0,0,153,23,1,0,0,0,154,152,1,0,0,0,
		155,160,3,26,13,0,156,157,5,20,0,0,157,159,3,26,13,0,158,156,1,0,0,0,159,
		162,1,0,0,0,160,158,1,0,0,0,160,161,1,0,0,0,161,25,1,0,0,0,162,160,1,0,
		0,0,163,165,3,28,14,0,164,166,5,28,0,0,165,164,1,0,0,0,165,166,1,0,0,0,
		166,27,1,0,0,0,167,177,5,1,0,0,168,169,5,21,0,0,169,170,3,18,9,0,170,171,
		5,22,0,0,171,177,1,0,0,0,172,177,3,36,18,0,173,177,3,66,33,0,174,177,3,
		58,29,0,175,177,3,60,30,0,176,167,1,0,0,0,176,168,1,0,0,0,176,172,1,0,
		0,0,176,173,1,0,0,0,176,174,1,0,0,0,176,175,1,0,0,0,177,29,1,0,0,0,178,
		187,5,2,0,0,179,187,5,3,0,0,180,187,5,4,0,0,181,187,5,5,0,0,182,183,5,
		23,0,0,183,184,3,32,16,0,184,185,5,24,0,0,185,187,1,0,0,0,186,178,1,0,
		0,0,186,179,1,0,0,0,186,180,1,0,0,0,186,181,1,0,0,0,186,182,1,0,0,0,187,
		31,1,0,0,0,188,193,3,34,17,0,189,190,5,19,0,0,190,192,3,34,17,0,191,189,
		1,0,0,0,192,195,1,0,0,0,193,191,1,0,0,0,193,194,1,0,0,0,194,33,1,0,0,0,
		195,193,1,0,0,0,196,199,3,30,15,0,197,199,5,1,0,0,198,196,1,0,0,0,198,
		197,1,0,0,0,199,207,1,0,0,0,200,203,5,25,0,0,201,204,3,30,15,0,202,204,
		5,1,0,0,203,201,1,0,0,0,203,202,1,0,0,0,204,206,1,0,0,0,205,200,1,0,0,
		0,206,209,1,0,0,0,207,205,1,0,0,0,207,208,1,0,0,0,208,35,1,0,0,0,209,207,
		1,0,0,0,210,224,3,38,19,0,211,224,5,30,0,0,212,213,5,31,0,0,213,224,3,
		38,19,0,214,217,5,32,0,0,215,218,3,38,19,0,216,218,5,1,0,0,217,215,1,0,
		0,0,217,216,1,0,0,0,218,224,1,0,0,0,219,220,5,38,0,0,220,221,5,20,0,0,
		221,222,5,32,0,0,222,224,3,38,19,0,223,210,1,0,0,0,223,211,1,0,0,0,223,
		212,1,0,0,0,223,214,1,0,0,0,223,219,1,0,0,0,224,37,1,0,0,0,225,231,5,33,
		0,0,226,227,5,33,0,0,227,228,5,20,0,0,228,231,5,33,0,0,229,231,5,34,0,
		0,230,225,1,0,0,0,230,226,1,0,0,0,230,229,1,0,0,0,231,39,1,0,0,0,232,234,
		3,42,21,0,233,232,1,0,0,0,233,234,1,0,0,0,234,241,1,0,0,0,235,237,5,25,
		0,0,236,238,3,42,21,0,237,236,1,0,0,0,237,238,1,0,0,0,238,240,1,0,0,0,
		239,235,1,0,0,0,240,243,1,0,0,0,241,239,1,0,0,0,241,242,1,0,0,0,242,244,
		1,0,0,0,243,241,1,0,0,0,244,245,5,22,0,0,245,41,1,0,0,0,246,251,3,44,22,
		0,247,248,7,0,0,0,248,250,3,44,22,0,249,247,1,0,0,0,250,253,1,0,0,0,251,
		249,1,0,0,0,251,252,1,0,0,0,252,43,1,0,0,0,253,251,1,0,0,0,254,259,3,46,
		23,0,255,256,5,11,0,0,256,258,3,46,23,0,257,255,1,0,0,0,258,261,1,0,0,
		0,259,257,1,0,0,0,259,260,1,0,0,0,260,45,1,0,0,0,261,259,1,0,0,0,262,267,
		3,48,24,0,263,264,7,1,0,0,264,266,3,48,24,0,265,263,1,0,0,0,266,269,1,
		0,0,0,267,265,1,0,0,0,267,268,1,0,0,0,268,47,1,0,0,0,269,267,1,0,0,0,270,
		275,3,50,25,0,271,272,7,2,0,0,272,274,3,50,25,0,273,271,1,0,0,0,274,277,
		1,0,0,0,275,273,1,0,0,0,275,276,1,0,0,0,276,49,1,0,0,0,277,275,1,0,0,0,
		278,283,3,52,26,0,279,280,5,6,0,0,280,282,3,52,26,0,281,279,1,0,0,0,282,
		285,1,0,0,0,283,281,1,0,0,0,283,284,1,0,0,0,284,51,1,0,0,0,285,283,1,0,
		0,0,286,288,3,54,27,0,287,289,5,18,0,0,288,287,1,0,0,0,288,289,1,0,0,0,
		289,53,1,0,0,0,290,291,7,1,0,0,291,294,3,54,27,0,292,294,3,56,28,0,293,
		290,1,0,0,0,293,292,1,0,0,0,294,55,1,0,0,0,295,303,3,30,15,0,296,297,5,
		21,0,0,297,298,3,2,1,0,298,299,5,22,0,0,299,303,1,0,0,0,300,303,3,68,34,
		0,301,303,3,20,10,0,302,295,1,0,0,0,302,296,1,0,0,0,302,300,1,0,0,0,302,
		301,1,0,0,0,303,57,1,0,0,0,304,308,5,38,0,0,305,306,7,3,0,0,306,308,5,
		38,0,0,307,304,1,0,0,0,307,305,1,0,0,0,308,59,1,0,0,0,309,311,3,62,31,
		0,310,309,1,0,0,0,310,311,1,0,0,0,311,312,1,0,0,0,312,313,5,39,0,0,313,
		61,1,0,0,0,314,316,5,29,0,0,315,314,1,0,0,0,315,316,1,0,0,0,316,317,1,
		0,0,0,317,318,3,64,32,0,318,63,1,0,0,0,319,320,5,38,0,0,320,65,1,0,0,0,
		321,322,5,35,0,0,322,323,3,40,20,0,323,67,1,0,0,0,324,330,5,36,0,0,325,
		327,7,3,0,0,326,325,1,0,0,0,326,327,1,0,0,0,327,328,1,0,0,0,328,330,5,
		37,0,0,329,324,1,0,0,0,329,326,1,0,0,0,330,331,1,0,0,0,331,332,3,40,20,
		0,332,69,1,0,0,0,38,78,86,94,102,110,117,123,132,139,145,152,160,165,176,
		186,193,198,203,207,217,223,230,233,237,241,251,259,267,275,283,288,293,
		302,307,310,315,326,329
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
